config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :players
  root 'teams#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
    @teams = Team.all
  end

  def show
    @player = Player.find(params[:id])
    if @player.team_id != nil
      @team = Team.find(@player.team_id)
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    redirect_to(players_path)
  end

  def edit
    @player = Player.find(params[:id])
    @teams = Team.all
  end

  def update
    player = Player.find(params[:id])
    player.update(player_params)
    redirect_to(players_path)
  end

  def create
    Player.create(player_params)
    redirect_to(players_path)
  end

  private

    def player_params
      params.require(:player).permit(:player_name, :position, :player_number, :snitch_catch_count, :team_id)
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def show
    @team = Team.find(params[:id])
  end

  def destroy
    team = Team.find(params[:id])
    team.destroy
    redirect_to(teams_path)
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    team = Team.find(params[:id])
    team.update(team_params)
    redirect_to(teams_path)
  end

  def create
    Team.create(team_params)
    redirect_to(teams_path)
  end

  private

    def team_params
      params.require(:team).permit(:name, :image, :founded, :mascot, :league, :last_position, :ground)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyLeague</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <li> <%= link_to('Teams', teams_path) %> </li>
    <li> <%= link_to('Players', players_path) %> </li>
    <li> <%= link_to('New Team',new_team_path) %> </li>
    <li> <%= link_to('New Player',new_player_path) %> </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/players/edit.html.erb
<%= form_for @player do |f| %>
  <%= f.label :player_name %>
  <%= f.text_field :player_name %>
  <br>
  <%= f.label :position %>
  <%= f.text_field :position %>
  <br>
  <%= f.label :player_number %>
  <%= f.text_field :player_number %>
  <br>
  <%= f.label :snitch_catch_count %>
  <%= f.text_field :snitch_catch_count %>
  <br>
  <br>
  <%= f.label :team_id, "Team" %>
  <%= f.collection_select(:team_id, @teams, :id, :name, prompt: "Who do they play for?") %>
  <br>
  <br>
  <%= f.submit 'Update Player!' %>
<% end %>

app/views/players/index.html.erb
<% @players.each do |player| %>
  <h2><%= player.player_name %></h2>
  <br>
  <%= link_to("Show #{player.player_name}", player_path(player)) %>
  <br>
  <%= button_to('Delete Player', player_path(player), method: :delete, data: {confirm: 'Delete player? Are you sure?!'} ) %>
  <%= link_to('Edit Player', edit_player_path(player)) %>
  <br>
  <br>
<% end %>

app/views/players/new.html.erb
<%= form_for @player do |f| %>
  <%= f.label :player_name %>
  <%= f.text_field :player_name %>
  <br>
  <%= f.label :position %>
  <%= f.text_field :position %>
  <br>
  <%= f.label :player_number %>
  <%= f.text_field :player_number %>
  <br>
  <%= f.label :snitch_catch_count %>
  <%= f.text_field :snitch_catch_count %>
 <br>
 <br>
 <%= f.label :team_id, "Team" %>
 <%= f.collection_select(:team_id, @teams, :id, :name, prompt: "Who do they play for?") %>
  <br>
  <br>
  <%= f.submit 'Create Player!' %>
<% end %>

app/views/players/show.html.erb
<h1> <%= @player.player_name %> </h1>
<br>
<p> <%= @player.player_name %>'s position is <%= @player.position %> </p>
<p> <%= @player.player_name %>'s number is <%= @player.player_number %> and they have caught the snitch <%= @player.snitch_catch_count %> times. </p>
<% if @player.team_id == nil %>
    <p><%= @player.player_name %> thinks they're far too good to play for a team.</p>
    <% else %>
    <p><%= @player.player_name %> plays for <%= @team.name %> </p>
<% end %>
<br>